# Generated by Django 2.1.2 on 2018-11-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
