# Generated by Django 2.1.2 on 2018-11-20 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(default='someone', max_length=250),
            preserve_default=False,
        ),
    ]
