# Generated by Django 2.1.2 on 2018-11-21 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_sender'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=25)),
                ('uid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
    ]
