# Generated by Django 2.1.2 on 2018-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20181121_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
