# Generated by Django 2.1.2 on 2018-11-25 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181121_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='uid',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
