# Generated by Django 2.1.2 on 2018-11-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20181125_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='user',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
